name: 'Experiment #1'
on:
  workflow_dispatch:
    inputs:
      name:
        description: "123"
        default: "123"

jobs:
    experiment_1:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Read %file%
          id: package
          uses: juliangruber/read-file-action@v1
          with:
            path: ./README.md
        - name: Echo %file%
          run: echo "${{ steps.package.outputs.content }}"