name: 'Experiment #1'
on: workflow-dispatch

jobs:
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3
  - name: Read %file%
    id: package
    uses: juliangruber/read-file-action@v1
    with:
      path: ./README.md
  - name: Echo %file%
    run: echo "${{ steps.package.outputs.content }}"