#____________________________________________
# GitHub Action Part-1 - work1991
#
# Copyleft (c) Nazar Hets 2023.
#____________________________________________
name: My-GitHubActions-work1991

on:
  workflow_dispatch:
    inputs:
      name:
        description: "123"
        default: "123"

  push:
    branches:
    - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing job"
    
  my_deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Print Hello Message
        run: echo "Hello World from Deploy job"
    
