#____________________________________________
# GitHub Action Part-1 - work1991
#
# Copyleft (c) Nazar Hets 2023.
#____________________________________________
name: My-GitHubActions-work1991

on:
  workflow_dispatch:
    inputs:
      customfield: 
        description: "123"
        default: "123"

      customfield1: 
        description: "321"
        default: "321"

  push:
    branches:
    - main
    - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "${{ github.event.inputs.customfield }}${{ github.event.inputs.customfield1}}" | rev |tr '[a-z]' '[A-Z]'
     
    
  my_deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Print Hello Message
        run: echo "Hello World from Deploy job"
    
name: learn-github-actions
  run-name: ${{ github.actor }} is learning GitHub Actions
  on: [push]
  jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
