name: My-GitHubActions-nazar_hets_work

on:
  workflow_dispatch:
    inputs:
      customfield: 
        description: "123"
        default: "123"

      customfield1: 
        description: "321"
        default: "321"

  push:
    branches:
    - main
    - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v3
            with:
              node-version: '18.16.1'
          - run: ls -al
          - run: npm --version
          - run: npm install 
          

      
          
    
            
      
 
         